---
title: Law Office of Linda Cornelius
# Configuration
permalink: "/:slug/"
collections:
  practice:
    output: true
exclude:
  - gulpfile.js
  - package.json
  - Gemfile
  - _styles
  - node_modules
env: production
gems:
  - octopress-minify-html
  - jekyll-sitemap