---
title: Law Office of Linda Cornelius
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  practice:
    title: Practice
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:slug/"
exclude:
- gulpfile.js
- package.json
- Gemfile
- _styles
- node_modules
env: production
